UNSUPPORTED_STATISTICS_TYPE = "Unsupported Statistics Type"
INVALID_VALUE = "INVALID VALUE"
TEMPERATURE = "temperature"
SOC = "soc"
SENSOR_DATA_FORMAT = '{{"{0}":{1}, "{2}":{3}}}\n'
SENSOR_INVALID_DATA_FORMAT = '{{"{0}":"{1}", "{2}":{3}}}\n'
MINIMUM = "Min"
MAXIMUM = "Max"
SIMPLE_MOVING_AVERAGE = "SMA"
MEDIAN = "Median"